archivesspace.archivesspace_type.*:
  type: config_entity
  label: 'ArchivesSpace type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
field.field_settings.as_extent:
  type: mapping
  label: 'Default AS Extent widget settings'
  mapping:
    extent_types:
      type: sequence
      label: 'Extent Types'
      sequence:
        - type: string
